version: '3'

services:

  nginx:
    image: nginx:1.14.0
    volumes:
      - ./etc/nginx/:/etc/nginx/
      - ./certs/nginx:/etc/nginx/certs
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
