version: '3'

networks:
  dmz_network:
    driver: bridge

services:
  nginx:
    image: nginx:1.12-alpine
    volumes:
      - ./etc/nginx/:/etc/nginx/
    ports:
      - "80:80"
      - "443:443"
    #restart: always
    depends_on:
      - jenkins
    networks:
      dmz_network:

  jenkins:
    image: jenkins
    #restart: always
    ports:
      - "8080:8080"
      - "50000:50000"
    expose:
      - 8080
      - 50000
    volumes:
      - jenkins_home:/var/jenkins_home
    #environment:
    #  - JENKINS_ARG="--prefix=/jenkins"
    #  - JENKINS_OPTS="--prefix=/jenkins"
    networks:
      dmz_network:

volumes:
  jenkins_home:
